openapi: 3.0.0
info:
  title: TicketTrackerBot
  description: Bot для получения данных об авиабилетах
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /search/routes:
    post:
      summary: Поиск по направлению
      description: Отправляет запрос на внешний сервис для поиска авиабилетов
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchTicketsRequest'
      responses:
        '200':
          description: Успешный ответ со статусом заявки
        '400':
          description: Некорректные параметры запроса
        '500':
          description: Ошибка работы сервера

components:
  schemas:
    SearchTicketsRequest:
      type: object
      properties:
        currency:
          type: string
          description: Код валюты
        from_date:
          type: string
          description: Дата начала окна перелета
          format: date
        to_date:
          type: string
          description: Дата окончания окна перелета
          format: date
        from_place:
          type: string
          description: Аэропорт вылета
        to_place:
          type: string
          description: Пункт назначения
        cost:
          type: number
          format: double
          description: Предполагаемая стоимость билетов
      example:
        from_date: 2024-10-10
        to_date: 2025-10-12
        from_place: VVO
        to_place: LED
        currency: RUB
        cost: 20000.0

