app:
  aviasalesBaseUrl: https://api.travelpayouts.com/aviasales/v3/grouped_prices
  aviasalesApiKey: ${AVIASALES_TOKEN}
  scheduler:
    enable: true
    interval: 15s

kafka-producer:
  acks: all
  batch-size: 1024
  max-request-size: 1024
  linger-ms: 5000
  bootstrap-server:  127.0.0.1:9092
  topic-prop:
    name: responses
    partitions: 1
    replicas: 1

kafka-consumer:
  bootstrap-server: 127.0.0.1:9092
  enable-auto-commit: false
  fetch-max-byte: 1024
  max-poll-records: 5
  max-poll-interval: 5
  group-id: listen
  isolation-level: read_committed
  topic-prop:
    name: queries
    partitions: 1
    replicas: 1

spring:
  application:
    name: scrapper
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: migrations/db.changelog-master.yml

server:
  port: 8090